# 默认主题 (Notion Style)
name: default
description: "Clean, minimal, Notion-like black and white style"
author: Antigravity

# Global Styles
body_style: "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.7; color: #37352f;"

# Container
container_style: "padding: 20px; background-color: #ffffff;"

# Elements
h1_style: "font-size: 30px; font-weight: 700; color: #37352f; margin-top: 40px; margin-bottom: 10px; line-height: 1.3;"
h2_style: "font-size: 24px; font-weight: 600; color: #37352f; margin-top: 30px; margin-bottom: 10px; border-bottom: 1px solid #e0e0e0; padding-bottom: 8px;"
h3_style: "font-size: 20px; font-weight: 600; color: #37352f; margin-top: 20px; margin-bottom: 8px;"

p_style: "margin-bottom: 16px; text-align: justify;"

strong_style: "font-weight: 600; color: #37352f;"

blockquote_style: "border-left: 3px solid #37352f; padding-left: 14px; margin: 16px 0; color: #37352f; font-style: italic;"

ul_style: "list-style-type: disc; margin-bottom: 16px; padding-left: 20px;"
ol_style: "margin-bottom: 16px; padding-left: 20px;"
li_style: "margin-bottom: 6px;"

pre_style: "background-color: #f7f6f3; color: #37352f; padding: 16px; border-radius: 4px; overflow-x: auto; margin: 16px 0; font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace; font-size: 14px;"
code_style: "font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace; background-color: #f7f6f3; padding: 2px 4px; border-radius: 2px; color: #eb5757;"

link_style: "color: #37352f; text-decoration: underline; text-decoration-color: #a0a0a0;"
image_style: "display: block; margin: 24px auto; max-width: 100%; border-radius: 4px;"
